<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="1" skipped="0" tests="4" time="0.105" timestamp="2023-07-18T12:30:09.290497" hostname="BMINNB341-1910"><testcase classname="test_multiplication" name="test_multiplication_11[1-11]" time="0.001" /><testcase classname="test_multiplication" name="test_multiplication_11[2-22]" time="0.001" /><testcase classname="test_multiplication" name="test_multiplication_11[3-33]" time="0.001" /><testcase classname="test_multiplication" name="test_multiplication_11[4-49]" time="0.001"><failure message="assert (11 * 4) == 49">num = 4, output = 49

    @pytest.mark.parametrize("num, output", [(1, 11), (2, 22), (3, 33), (4, 49)])
    def test_multiplication_11(num, output):
&gt;       assert 11*num == output
E       assert (11 * 4) == 49

test_multiplication.py:6: AssertionError</failure></testcase></testsuite></testsuites>